from django.core.management.base import BaseCommand, CommandError
from django.contrib.auth import get_user_model

from users.models import Department, Designation

User = get_user_model()


class Command(BaseCommand):
    help = "Create multiple users using json file"

    def handle(self, *args, **options):

        employees = [
	{
		"first_name": "Terry",
		"last_name": "Medhurst",
		"middle_name": "Smitham",
		"is_hr": False,
		"is_employee": True,
		"start_date": "2021-07-05",
		"gender": "male",
		"email": "atuny0@sohu.com",
		"phone": "637916758914",
		"date_of_birth": "2000-12-25",
		"designation": "Cost Accountant",
		"department": "Accounting",
		"password": "user@mail.com",
	},
	{
		"first_name": "Sheldon",
		"last_name": "Quigley",
		"middle_name": "Cole",
		"is_hr": False,
		"is_employee": True,
		"start_date": "2019-05-01",
		"gender": "male",
		"email": "hbingley1@plala.or.jp",
		"phone": "813 117 7139",
		"date_of_birth": "2003-08-02",
		"designation": "Sales Representative",
		"department": "Sales",
		"password": "user@mail.com",
	},
	{
		"first_name": "Terrill",
		"last_name": "Hills",
		"middle_name": "Hoeger",
		"is_hr": False,
		"is_employee": True,
		"start_date": "2018-12-01",
		"gender": "male",
		"email": "rshawe2@51.la",
		"phone": "63 739 292 7942",
		"date_of_birth": "1992-12-30",
		"designation": "SEO Specialist",
		"department": "Marketing",
		"password": "user@mail.com",
	},
	{
		"first_name": "Miles",
		"last_name": "Cummerata",
		"middle_name": "Maggio",
		"is_hr": False,
		"is_employee": True,
		"start_date": "2022-08-11",
		"gender": "male",
		"email": "yraigatt3@nature.com",
		"phone": "86 461 145 4186",
		"date_of_birth": "1969-01-16",
		"designation": "Software Engineer",
		"department": "Information Technology",
		"password": "user@mail.com",
	},
	{
		"first_name": "Mavis",
		"last_name": "Schultz",
		"middle_name": "Yundt",
		"is_hr": False,
		"is_employee": True,
		"start_date": "2022-04-06",
		"gender": "male",
		"email": "kmeus4@upenn.edu",
		"phone": "72 285 771 1911",
		"date_of_birth": "1968-11-03",
		"designation": "Software Tester",
		"department": "Information Technology",
		"password": "user@mail.com",
	},
	{
		"first_name": "Alison",
		"last_name": "Reichert",
		"middle_name": "Franecki",
		"is_hr": False,
		"is_employee": True,
		"start_date": "2021-12-01",
		"gender": "female",
		"email": "jtreleven5@nhs.uk",
		"phone": "+351 527 735 3642",
		"date_of_birth": "1969-07-21",
		"designation": "Data Science",
		"department": "Information Technology",
		"password": "user@mail.com",
	},
	{
		"first_name": "Oleta",
		"last_name": "Abbott",
		"middle_name": "Wyman",
		"is_hr": False,
		"is_employee": True,
		"start_date": "2020-06-01",
		"gender": "female",
		"email": "dpettegre6@columbia.edu",
		"phone": "+62 640 802 7111",
		"date_of_birth": "1982-02-21",
		"designation": "Sales Associate",
		"department": "Sales",
		"password": "user@mail.com",
	},
	{
		"first_name": "Ewell",
		"last_name": "Mueller",
		"middle_name": "Durgan",
		"is_hr": False,
		"is_employee": True,
		"start_date": "2017-02-03",
		"gender": "male",
		"email": "ggude7@chron.com",
		"phone": "86 946 297 2275",
		"date_of_birth": "1964-08-24",
		"designation": "Brand Manager",
		"department": "Marketing",
		"password": "user@mail.com",
	},
	{
		"first_name": "Demetrius",
		"last_name": "Corkery",
		"middle_name": "Gleason",
		"is_hr": False,
		"is_employee": True,
		"start_date": "2019-11-01",
		"gender": "male",
		"email": "nloiterton8@aol.com",
		"phone": "86 356 590 9727",
		"date_of_birth": "1971-03-11",
		"designation": "Writer",
		"department": "Marketing",
		"password": "user@mail.com",
	},
	{
		"first_name": "Eleanora",
		"last_name": "Price",
		"middle_name": "Cummings",
		"is_hr": False,
		"is_employee": True,
		"start_date": "2019-10-09",
		"gender": "female",
		"email": "umcgourty9@jalbum.net",
		"phone": "60 184 408 0824",
		"date_of_birth": "1958-08-11",
		"designation": "Bookkeeper",
		"department": "Accounting",
		"password": "user@mail.com",
	},
	{
		"first_name": "Marcel",
		"last_name": "Jones",
		"middle_name": "Smith",
		"is_hr": True,
		"is_employee": False,
		"start_date": "2021-08-14",
		"gender": "male",
		"email": "acharlota@liveinternet.ru",
		"phone": "67 253 210 0344",
		"date_of_birth": "1961-09-12",
		"designation": "HR Coordinator",
		"department": "Human Resource",
		"password": "user@mail.com",
	},
	{
		"first_name": "Assunta",
		"last_name": "Rath",
		"middle_name": "Heller",
		"is_hr": True,
		"is_employee": False,
		"start_date": "2020-09-11",
		"gender": "female",
		"email": "rhallawellb@dropbox.com",
		"phone": "80 962 542 6549",
		"date_of_birth": "1990-12-14",
		"designation": "Recruiter",
		"department": "Human Resource",
		"password": "user@mail.com",
	},
	{
		"first_name": "Trace",
		"last_name": "Douglas",
		"middle_name": "Lemke",
		"is_hr": False,
		"is_employee": True,
		"start_date": "2022-04-14",
		"gender": "male",
		"email": "lgribbinc@posterous.com",
		"phone": "09 937 3468",
		"date_of_birth": "1967-07-23",
		"designation": "Sales Associate",
		"department": "Sales",
		"password": "user@mail.com",
	},
	{
		"first_name": "Enoch",
		"last_name": "Lynch",
		"middle_name": "Heidenreich",
		"is_hr": False,
		"is_employee": True,
		"start_date": "2021-12-01",
		"gender": "male",
		"email": "mturleyd@tumblr.com",
		"phone": "912 100 5118",
		"date_of_birth": "1979-08-25",
		"designation": "Sales Representative",
		"department": "Sales",
		"password": "user@mail.com",
	},
	{
		"first_name": "Jeanne",
		"last_name": "Halvorson",
		"middle_name": "Cummerata",
		"is_hr": False,
		"is_employee": True,
		"start_date": "2014-01-08",
		"gender": "female",
		"email": "kminchelle@qq.com",
		"phone": "6 581 108 7855",
		"date_of_birth": "1996-02-02",
		"designation": "Sales Associate",
		"department": "Sales",
		"password": "user@mail.com",
	},
	{
		"first_name": "Trycia",
		"last_name": "Fadel",
		"middle_name": "Rosenbaum",
		"is_hr": False,
		"is_employee": True,
		"start_date": "2023-02-06",
		"gender": "female",
		"email": "dpierrof@vimeo.com",
		"phone": "0 833 708 0340",
		"date_of_birth": "1963-07-03",
		"designation": "Brand Manager",
		"department": "Marketing",
		"password": "user@mail.com",
	},
	{
		"first_name": "Bradford",
		"last_name": "Prohaska",
		"middle_name": "Bins",
		"is_hr": False,
		"is_employee": True,
		"start_date": "2019-03-07",
		"gender": "male",
		"email": "vcholdcroftg@ucoz.com",
		"phone": "0 874 628 3710",
		"date_of_birth": "1975-10-20",
		"designation": "Finance clerk",
		"department": "Accounting",
		"password": "user@mail.com",
	},
	{
		"first_name": "Arely",
		"last_name": "Skiles",
		"middle_name": "Monahan",
		"is_hr": False,
		"is_employee": True,
		"start_date": "2019-01-06",
		"gender": "male",
		"email": "sberminghamh@chron.com",
		"phone": "55 886 766 8617",
		"date_of_birth": "1958-02-05",
		"designation": "Financial auditor",
		"department": "Accounting",
		"password": "user@mail.com",
	},
	{
		"first_name": "Gust",
		"last_name": "Purdy",
		"middle_name": "Abshire",
		"is_hr": False,
		"is_employee": True,
		"start_date": "2021-11-01",
		"gender": "male",
		"email": "bleveragei@so-net.ne.jp",
		"phone": "6 886 889 0258",
		"date_of_birth": "1989-10-15",
		"designation": "Accounting officer",
		"department": "Accounting",
		"password": "user@mail.com",
	},
	{
		"first_name": "Lenna",
		"last_name": "Renner",
		"middle_name": "Schumm",
		"is_hr": False,
		"is_employee": True,
		"start_date": "2023-10-01",
		"gender": "female",
		"email": "aeatockj@psu.edu",
		"phone": "04 601 7177",
		"date_of_birth": "1980-01-19",
		"designation": "Data Engineer",
		"department": "Information Technology",
		"password": "user@mail.com",
	},
]

        for employee in employees:

            User.objects.create(
                first_name= employee["first_name"],
                last_name= employee["last_name"],
                middle_name= employee["middle_name"],
                is_hr= employee["is_hr"],
                is_employee= employee["is_employee"],
                start_date= employee["start_date"],
                gender= employee["gender"],
                email= employee["email"],
                phone= employee["phone"],
                date_of_birth= employee["date_of_birth"],
                department= Department.objects.get(name=employee["department"]),
                designation= Designation.objects.get(name=employee["designation"]),
               
                password= employee["password"],
            )
        self.stdout.write("user created")


        