# Generated by Django 4.2.3 on 2023-08-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leavebalance_days_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='days_left',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
