# Generated by Django 4.2.3 on 2023-08-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_alter_leavebalance_days_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='days_left',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
