# Generated by Django 4.2.3 on 2023-08-03 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_alter_leavebalance_days_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavebalance',
            old_name='days_left',
            new_name='number_of_days',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='leave_application',
        ),
    ]
